language: objective-c
osx_image: xcode8

before_install:

  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:

  - pod lib lint
  - xcodebuild clean build test -project Validator.xcodeproj -scheme Validator -sdk iphonesimulator10.0 -destination "OS=10.0,name=iPhone 6" -enableCodeCoverage YES | xcpretty

after_success:

  - bash <(curl -s https://codecov.io/bash)